# Sample configuration file, see CONFIG.md for explanation.
refresh: 10
theme: default
sort: change
reverse: true
prices: CAD
stocks:
    - MSFT # stock
    - VTV # etf
    - ^DJI # index
cryptos:
    - BTC # crypto
    - ETH # crypto
forexes:
    - CADUSD # forex
    - USDGBP # forex
others:
    - ^TNX # bond
    - GC=F # future
    - 600519.SS # sse
